config/routes.rb
Rails.application.routes.draw do
  resources :machine_processes do
    collection do
      post :recipe_form
    end
  end
  resources :machines
  resources :recipe_inputs
  resources :recipes
  resources :resources do
    collection do
      put :reorder
    end
    member do
      get :resource_tree
      get :process_tree
    end
  end
  devise_for :admins

  get '/calc' => 'calc#calc', as: :calc
  post '/calc' => 'calc#calc'

  root 'calc#calc'
end

app/controllers/calc_controller.rb
class CalcController < ApplicationController
  def calc
    return render unless params.key?(:resource) && params.key?(:amount)

    @amount = BigDecimal.new(params.fetch(:amount))
    @resource = Resource.find params[:resource]

    # @resource_tree = SatisfactoryCalculator.resource_tree(@amount, @resource).values
    @process_tree = SatisfactoryCalculator.process_tree(@amount, @resource).values
  end
end

app/views/calc/_calc.html.erb
<%= form_tag(calc_path) do %>
  <%= select_tag :resource, option_groups_from_collection_for_select(
      Resource.all.group_by(&:category).transform_keys { |c| Resource.category_name(c) },
      :second, :first, :id, :name, @resource&.id) %>
  <%= number_field_tag :amount, @amount || 1, step: :any %>
  <%= submit_tag 'Calc' %>
<% end %>

app/views/calc/calc.html.erb
<%= render 'calc' %>
<% if @resource_tree.present? %>
  <div id="resource-tree"></div>
  <%= react_component 'ResourceGraph', dagData: @resource_tree.as_json %>
<% end %>
<% if @process_tree.present? %>
  <%= react_component 'ResourceGraph', dagData: @process_tree.as_json %>
<% end %>

app/views/calc/index.html.erb
<div class="list-group">
  <%= link_to 'machines', machines_path, class: 'list-group-item list-group-item-action' %>
  <%= link_to 'resources', resources_path, class: 'list-group-item list-group-item-action' %>
  <%= link_to 'recipes', recipes_path, class: 'list-group-item list-group-item-action' %>
  <%= link_to 'recipe inputs', recipe_inputs_path, class: 'list-group-item list-group-item-action' %>
  <%= link_to 'machine processes', machine_processes_path, class: 'list-group-item list-group-item-action' %>
</div>
<%= render 'calc' %>