config/routes.rb
Rails.application.routes.draw do
  resources :machine_processes do
    collection do
      post :recipe_form
    end
  end
  resources :machines
  resources :recipe_inputs
  resources :recipes
  resources :resources do
    collection do
      put :reorder
    end
    member do
      get :resource_tree
      get :process_tree
    end
  end
  devise_for :admins

  get '/calc' => 'calc#calc', as: :calc
  post '/calc' => 'calc#calc'

  root 'calc#calc'
end

app/controllers/machine_processes_controller.rb
class MachineProcessesController < AdminController
  before_action :set_machine_process, only: [:show, :edit, :update, :destroy]

  # GET /machine_processes
  # GET /machine_processes.json
  def index
    @machine_processes = MachineProcess.joins(recipe: :output).merge(Resource.all)
  end

  # GET /machine_processes/1
  # GET /machine_processes/1.json
  def show
  end

  # GET /machine_processes/new
  def new
    @machine_process = MachineProcess.new(machine_process_params(false))
  end

  # GET /machine_processes/1/edit
  def edit
  end

  # POST /machine_processes
  # POST /machine_processes.json
  def create
    @machine_process = MachineProcess.new(machine_process_params)

    respond_to do |format|
      if @machine_process.save
        format.html { redirect_to @machine_process, notice: 'Machine process was successfully created.' }
        format.json { render :show, status: :created, location: @machine_process }
      else
        format.html { render :new }
        format.json { render json: @machine_process.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /machine_processes/1
  # PATCH/PUT /machine_processes/1.json
  def update
    respond_to do |format|
      if @machine_process.update(machine_process_params)
        format.html { redirect_to @machine_process, notice: 'Machine process was successfully updated.' }
        format.json { render :show, status: :ok, location: @machine_process }
      else
        format.html { render :edit }
        format.json { render json: @machine_process.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /machine_processes/1
  # DELETE /machine_processes/1.json
  def destroy
    @machine_process.destroy
    respond_to do |format|
      format.html { redirect_to machine_processes_url, notice: 'Machine process was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def recipe_form
    @recipe = if params.key? :recipe_id
      Recipe.find_by id: params[:recipe_id]
    else
      Recipe.new do |r|
        params[:input_count].to_i.times { r.recipe_inputs.build } if params.key? :input_count
      end
    end

    render layout: false
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_machine_process
    @machine_process = MachineProcess.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def machine_process_params(require = true)
    return {} unless require || params.key?(:machine_process)
    params.require(:machine_process).permit(:recipe_id, :rate, :machine_id,
                                            recipe_attributes: [:id, :name, :output_id, :output_amount,
                                                                recipe_inputs_attributes: [:id, :resource_id, :amount]])
  end
end

app/helpers/machine_processes_helper.rb
module MachineProcessesHelper
end

app/views/machine_processes/_form.html.erb
<%= simple_form_for(@machine_process) do |f| %>
  <% if machine_process.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(machine_process.errors.count, "error") %> prohibited this machine_process from being saved:</h2>

      <ul>
        <% machine_process.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :machine_id, collection: Machine.all.map(&:options_for_select), include_blank: false %>
  </div>

  <div class="field">
    <%= f.input :rate %>
  </div>

  <div class="field">
    <%= f.input :recipe_id, collection: Recipe.all.map(&:options_for_select), prompt: 'Create New' %>
  </div>

  <div id="recipe_fields">
    <%= f.simple_fields_for :recipe do |ff| %>
      <%= render 'recipe_fields', f: ff %>
    <% end %>
  </div>

  <% content_for :javascripts do %>
    <script>
        $(function () {
            function updateRecipe() {
                const $select = $('#machine_process_recipe_id');

                const data = {authenticity_token: '<%= j form_authenticity_token(form_options: {action: recipe_form_machine_processes_path, method: 'post'}) %>'};

                if ($select.val()) {
                    data.recipe_id = $select.val();
                } else {
                    data.input_count = $('#machine_process_machine_id option:selected').data('inputs');
                }

                $('#recipe_fields').load("<%= j recipe_form_machine_processes_path %>", data);
            }

            function checkMachineInputs() {
                const inputs = $('#machine_process_machine_id option:selected').data('inputs');

                $('#machine_process_recipe_id option').prop('disabled', true);
                $('#machine_process_recipe_id option[data-inputs=' + inputs + ']').prop('disabled', false);
                $('#machine_process_recipe_id option[value=""]').prop('disabled', false);

                if ($('#machine_process_recipe_id').val() === '') {
                    updateRecipe();
                }
            }

            $(document).on('change', '#machine_process_machine_id', checkMachineInputs);
            $(document).on('change', '#machine_process_recipe_id', updateRecipe);

            checkMachineInputs();
            updateRecipe();
        });
    </script>
  <% end %>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/machine_processes/_recipe_fields.html.erb
<% f = f %>

<%= f.input :id, as: :hidden %>

<div class="field">
  <%= f.input :name %>
</div>

<div class="field">
  <%= f.input :output_id, label: 'output', collection: Resource.all %>
</div>

<div class="field">
  <%= f.input :output_amount %>
</div>

<% if f.object.recipe_inputs.any? %>
  <div>
    <strong>Inputs</strong>
    <div id="recipe_input_fields">
      <%= f.simple_fields_for :recipe_inputs do |fi| %>
        <%= render 'recipes/recipe_input_fields', f: fi, allow_remove: false %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/machine_processes/edit.html.erb
<h1>Editing Machine Process</h1>

<%= render 'form', machine_process: @machine_process %>

<%= link_to 'Show', @machine_process %> |
<%= link_to 'Back', machine_processes_path %>

app/views/machine_processes/index.html.erb
<% max_input_count = @machine_processes.joins(:machine).maximum('machines.input_count') %>
<h1>Machine Processes</h1>

<table class="table">
  <thead>
  <tr>
    <th>Recipe</th>
    <th>Output</th>
    <% max_input_count.times do |idx| %>
      <th>Input <%= idx + 1 %></th>
    <% end %>
    <th>Machine</th>
    <th></th>
  </tr>
  </thead>

  <% @machine_processes.group_by(&:category).each do |category, machine_processes| %>
    <thead>
    <tr>
      <th colspan="<%= max_input_count + 4 %>"><%= Resource.category_name category %></th>
    </tr>
    </thead>
    <tbody>
    <% machine_processes.each do |machine_process| %>
      <tr>
        <td><%= link_to machine_process.recipe.name, machine_process.recipe %></td>
        <td>
          <%= link_to_pluralized_object machine_process.per_minute, machine_process.recipe.output %>
          / min
        </td>
        <% max_input_count.times do |idx| %>
          <% input = machine_process.recipe.recipe_inputs[idx] %>
          <td>
            <% if input.present? %>
              <%= link_to_pluralized_object machine_process.per_minute(input.amount), input.resource %>
              / min
            <% end %>
          </td>
        <% end %>
        <td><%= link_to machine_process.machine.name, machine_process.machine %></td>
        <td>
          <div class="btn-group">
            <%= link_to fa_icon('eye'), machine_process, class: 'btn btn-sm btn-info' %>
            <%= link_to fa_icon('pencil'), edit_machine_process_path(machine_process), class: 'btn btn-sm btn-secondary' %>
            <%= link_to fa_icon('times'), machine_process, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-sm btn-danger' %></div>
        </td>
      </tr>
    <% end %>
    </tbody>
  <% end %>
</table>

<br>

<%= link_to fa_icon('plus', text: 'New Machine Process'), new_machine_process_path, class: 'btn btn-primary' %>

app/views/machine_processes/new.html.erb
<h1>New Machine Process</h1>

<%= render 'form', machine_process: @machine_process %>

<%= link_to 'Back', machine_processes_path %>

app/views/machine_processes/recipe_form.html.erb
<%= simple_fields_for :machine_process do |f| %>
  <%= f.simple_fields_for :recipe_attributes, @recipe do |ff| %>
    <%= render 'recipe_fields', f: ff %>
  <% end %>
<% end %>

app/views/machine_processes/show.html.erb
<p>
  <strong>Recipe:</strong>
  <%= link_to @machine_process.recipe.name, @machine_process.recipe %>
</p>
<p>
  <strong>Rate:</strong>
  <%= pluralize @machine_process.rate, 'second' %>
</p>

<p>
  <strong>Output: </strong>
  <%= link_to_pluralized_object @machine_process.per_minute, @machine_process.recipe.output %>
  / minute
  <%= link_to fa_icon('calculator'), calc_path(amount: @machine_process.per_minute, resource: @machine_process.recipe.output), class: 'btn btn-sm btn-info' %>
</p>

<p>
  <strong>Inputs:</strong>
</p>
<% @machine_process.recipe.recipe_inputs.each do |input| %>
  <p>
    <%= link_to_pluralized_object @machine_process.per_minute(input.amount), input.resource %>
    / minute
  </p>
<% end %>

<%= link_to 'Add Another', action: :new %> |
<%= link_to 'Edit', edit_machine_process_path(@machine_process) %> |
<%= link_to 'Back', machine_processes_path %>