config/routes.rb
Rails.application.routes.draw do
  resources :machine_processes do
    collection do
      post :recipe_form
    end
  end
  resources :machines
  resources :recipe_inputs
  resources :recipes
  resources :resources do
    collection do
      put :reorder
    end
    member do
      get :resource_tree
      get :process_tree
    end
  end
  devise_for :admins

  get '/calc' => 'calc#calc', as: :calc
  post '/calc' => 'calc#calc'

  root 'calc#calc'
end

app/views/resources/_form.html.erb
<%= simple_form_for(resource) do |form| %>
  <% if resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.input :name, autofocus: true %>
  </div>

  <div class="field">
    <%= form.input :category, collection: Resource::CATEGORIES.map(&:reverse), include_blank: false %>
  </div>

  <div class="actions">
    <%= form.submit %>
    <%= form.submit 'Save & Create Another' %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<h1>Resources</h1>

<table class="table">
  <% (Resource.categories.keys + [nil]).each do |category| %>
    <% resources = Resource.where(category: category) %>
    <thead>
    <tr>
      <th></th>
      <th colspan="2"><%= Resource.category_name category %> <%= link_to fa_icon('plus'), new_resource_path(resource: {category: category}), class: 'btn btn-link' %></th>
    </tr>
    </thead>
    <tbody class="sortable" data-category="<%= category %>">
    <% resources.each do |resource| %>
      <tr class="item" data-id="<%= resource.id %>">
        <td><%= fa_icon 'bars', class: 'handle' %></td>
        <td><%= link_to resource.name, resource %></td>
        <td>
          <div class="btn-group">
            <%= link_to fa_icon('plus'), new_machine_process_path(machine_process: {recipe_attributes: {output_id: resource}}), class: 'btn btn-sm btn-warning' if resource.recipes.none? %>
            <%= link_to fa_icon('pencil'), edit_resource_path(resource), class: 'btn btn-sm btn-secondary' %>
            <%= link_to fa_icon('times'), resource, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-sm btn-danger' %>
          </div>
        </td>
      </tr>
    <% end %>
    </tbody>
  <% end %>
</table>

<br>

<%= link_to fa_icon('plus', text: 'New Resource'), new_resource_path, class: 'btn btn-primary' %>

<% content_for :javascripts do %>
  <script>
      $(function () {
          $('.sortable').sortable({
              draggable: '.item',
              handle: '.handle',
              group: 'resources',
              onEnd: function (evt) {
                  const to = evt.to,
                      category = $(to).data('category'),
                      arr = $(to).sortable('toArray');
                  $.ajax({
                      method: 'PUT',
                      url: "<%= j reorder_resources_path %>",
                      data: {
                          authenticity_token: "<%= j form_authenticity_token(form_options: {action: reorder_resources_path, method: 'put'}) %>",
                          category: category,
                          ids: arr
                      }
                  });
              },
          });
      });
  </script>
<% end %>

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<h1>
  <%= @resource.name %><%= link_to fa_icon('pencil'), edit_resource_path(@resource), class: 'btn btn-sm btn-link' %>
</h1>

<div class="row mb-4">
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">
          Recipes
          <%= link_to fa_icon('plus'), new_machine_process_path(machine_process: {recipe_attributes: {output_id: @resource}}), class: 'btn btn-sm btn-outline-primary pull-right' %>
        </h5>
        <% if @resource.recipes.many? %>
          <ul class="nav nav-tabs card-header-tabs" role="tablist">
            <% @resource.recipes.each.with_index do |recipe, idx| %>
              <li class="nav-item">
                <%= link_to recipe.name, '#' + dom_id(recipe), id: dom_id(recipe) + '-tab', class: ['nav-link', ('active' if idx.zero?)], data: {toggle: 'tab'}, role: 'tab', 'aria-controls': dom_id(recipe), 'aria-selected': idx.zero? %>
              </li>
            <% end %>
          </ul>
        <% end %>
      </div>
      <div class="tab-content">
        <% @resource.recipes.each.with_index do |recipe, idx| %>
          <div class="tab-pane fade <%= 'show active' if idx.zero? %>" id="<%= dom_id(recipe) %>" role="tabpanel" aria-labelledby="<%= dom_id(recipe) %>-tab">
            <table class="table table-borderless m-0">
              <tbody>
              <% recipe.recipe_inputs.each do |input| %>
                <tr>
                  <td><%= input.amount %></td>
                  <td>
                    <%= link_to input.name.pluralize(input.amount), input %>
                  </td>
                  <td>
                    <%= recipe.machine_process.per_minute(input.amount).to_pretty_s %>
                  </td>
                </tr>
              <% end %>
              </tbody>
              <tfoot>
              <tr class="table-primary">
                <th><%= recipe.output_amount %></th>
                <th>
                  <%= link_to recipe.output.name.pluralize(recipe.output_amount), recipe.output %>
                </th>
                <th>
                  <%= recipe.machine_process.per_minute.to_pretty_s %>
                </th>
              </tr>
              </tfoot>
            </table>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <div class="card">
      <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs" role="tablist">
          <li class="nav-item">
            <%= link_to 'Resources', '#resource-tree', id: 'resource-tree-tab', class: 'nav-link active', data: {toggle: 'tab'}, role: 'tab', 'aria-controls': 'resource-tree', 'aria-selected': true %>
          </li>
          <li class="nav-item">
            <%= link_to 'Processes', '#process-tree', id: 'process-tree-tab', class: 'nav-link', data: {toggle: 'tab'}, role: 'tab', 'aria-controls': 'process-tree', 'aria-selected': false %>
          </li>
        </ul>
      </div>
      <div class="card-body tab-content">
        <div class="tab-pane fade show active" id="resource-tree" role="tabpanel" aria-labelledby="resource-tree-tab">
          <%= react_component 'ResourceCalc', resourceId: @resource.id, treePath: resource_tree_resource_path(@resource) %>
        </div>
        <div class="tab-pane fade" id="process-tree" role="tabpanel" aria-labelledby="process-tree-tab">
          <%= react_component 'ResourceCalc', resourceId: @resource.id, treePath: process_tree_resource_path(@resource) %>
        </div>
      </div>
    </div>
  </div>
</div>