config/routes.rb
Rails.application.routes.draw do
  resources :machine_processes do
    collection do
      post :recipe_form
    end
  end
  resources :machines
  resources :recipe_inputs
  resources :recipes
  resources :resources do
    collection do
      put :reorder
    end
    member do
      get :resource_tree
      get :process_tree
    end
  end
  devise_for :admins

  get '/calc' => 'calc#calc', as: :calc
  post '/calc' => 'calc#calc'

  root 'calc#calc'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SatisfactoryCalc</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application' %>

  <!-- jsDelivr :: Sortable :: Latest (https://www.jsdelivr.com/package/npm/sortablejs) -->
  <%= javascript_include_tag "//cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js" %>
  <!-- jsDelivr :: Sortable :: Latest (https://www.jsdelivr.com/package/npm/jquery-sortablejs) -->
  <%= javascript_include_tag "//cdn.jsdelivr.net/npm/jquery-sortablejs@latest/jquery-sortable.min.js" %>

  <%= yield :javascripts %>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">Satisfactory Calc</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%= nav_item root_path, 'Home' %>
      <%= nav_item machines_path, 'Machines' %>
      <%= nav_item resources_path, 'Resources' %>
      <%= nav_item recipes_path, 'Recipes' %>
      <%= nav_item machine_processes_path, 'Machine Processes' %>
    </ul>
    <span class="navbar-text">
      <% if admin_signed_in? %>
        Logged in as <strong><%= current_admin.email %></strong>.
        <%= link_to "Logout", destroy_admin_session_path, method: :delete, class: 'navbar-link' %>
      <% else %>
        <%= link_to "Login", new_admin_session_path, class: 'navbar-link' %>
      <% end %>
    </span>
  </div>
</nav>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>